FROM node:14

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 4200

CMD [ "npx", "webpack-dev-server", "--hot", "--host=0.0.0.0", "--public=localhost:4200", "--env", "development", "--config", "webpack.dev.js" ]