version: "3.8"
services:
  frontend:
    build: .
    container_name: appointto-frontend
    ports: 4300:4300
    volumes:
      - ./src:/app/src
      - ./public/assets:/app/public/assets
      - /app/node_modules
    stdin_open: true
    tty: true
