version: "3.8"
services:
  frontend:
    build: .
    container_name: eshramik-web-application
    ports: 
      - 4200:4200
    volumes:
      - ./src:/app/src
      - ./public/assets:/app/public/assets
      - /app/node_modules
    stdin_open: true
    tty: true
