FROM node:14

WORKDIR /app

ARG DEFAULT_PORT 4200

COPY package.json .

RUN npm install

COPY . .

EXPOSE $DEFAULT_PORT

CMD [ "npx", "webpack-dev-server", "--hot", "--host=0.0.0.0", "--public=localhost:$DEFAULT_PORT", "--env", "development", "--config", "config/webpack.dev.js" ]