name: deploy-container

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "src/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build React code
        run: |
          npm install
          npm run build --if-present

      - name: Add origin and deploy to heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:master -f