name: deploy-container

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "src/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one line script
        run: echo Hello world!
      - name: Run a multi line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
      # - run: npm install
      # - run: npm run build --if-present

      # - uses: chrislennon/action-aws-cli@v1.1
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}